version: '3'
name: scatter-protocol-resources
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: scatter-ipfs
    volumes:
      - ipfs-data:/data/ipfs
    ports:
        - "4001:4001"
        - "5001:5001"
        - "8080:8080"

  requestor-postgres:
    image: postgres
    ports:
      - "8701:5432"
    environment:
      POSTGRES_DB: requestor-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - requestor-postgres-data:/var/lib/postgresql/data

  trainer-postgres:
    image: postgres
    ports:
      - "8702:5432"
    environment:
      POSTGRES_DB: trainer-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - trainer-postgres-data:/var/lib/postgresql/data

  validator-postgres:
    image: postgres
    ports:
      - "8703:5432"
    environment:
      POSTGRES_DB: validator-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - validator-postgres-data:/var/lib/postgresql/data
  
  hardhat-network:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.hardhat
    image: hardhat-network:latest
    ports:
      - "8545:8545"

volumes:
  requestor-postgres-data:
  trainer-postgres-data:
  validator-postgres-data:
  ipfs-data:
