version: '3'
name: scatter-protocol-contracts
services:
  compiler:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.compile
    volumes:
      - ./contracts:/app/contracts
      - ./build:/app/build
      - ./protocol:/app/protocol
      - ./node_modules:/app/node_modules
      - ./contract-deploy.json:/app/contract-deploy.json
      - ./dockerfiles/entrypoints/entrypoint-compile.sh:/app/entrypoint-compile.sh
    entrypoint: ./entrypoint-compile.sh

  deployer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.deploy
    network_mode: host
    volumes:
      - ./scripts:/app/scripts
      - ./contracts:/app/contracts
      - ./:/app
      - ./dockerfiles/entrypoints/entrypoint-deploy.sh:/app/entrypoint-deploy.sh
    env_file:
      - .env
    entrypoint: ./entrypoint-deploy.sh
    depends_on:
      - compiler