import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ContextProvider from '@/contexts/ContextProvider'
import NavigationBar from '@/components/NavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          <main>
            <div className="bg-gray-100 h-screen overflow-y-hidden">
              <NavigationBar></NavigationBar>
              <main className='h-full pb-16'>
                {children}
              </main>
            </div>
          </main>
        </body>
      </ContextProvider>
    </html>)
}
